apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: sample-from-vault
  namespace: external-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: vault-backend
  target:
    name: sample-from-vault
  data:
    - secretKey: username
      remoteRef:
        key: app/demo
        property: username
