apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gitlab-runner

resources:
  - ../../base

patches:
  - target:
      kind: Deployment
      name: gitlab-runner
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: gitlab-runner
      spec:
        replicas: 2
        template:
          spec:
            containers:
            - name: gitlab-runner
              resources:
                requests:
                  memory: "256Mi"
                  cpu: "200m"
                limits:
                  memory: "512Mi"
                  cpu: "500m"
