apiVersion: v1
kind: ConfigMap
metadata:
  name: gitlab-runner-config
  namespace: gitlab-runner
data:
  config.toml: |
    concurrent = 10
    check_interval = 3
    
    [[runners]]
      name = "k3d-local-runner"
      url = "GITLAB_URL_PLACEHOLDER"
      token = "RUNNER_TOKEN_PLACEHOLDER"
      executor = "kubernetes"
      
      [runners.kubernetes]
        namespace = "gitlab-runner"
        image = "alpine:latest"
        privileged = true
