# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class K3dLocal < Formula
  desc "Cross-platform CLI for managing local k3d Kubernetes clusters with pre-configured components"
  homepage "https://github.com/gautampachnanda101/local-cluster-k3d"
  version "1.0.4"
  license "MIT"

  depends_on "docker" => :optional
  depends_on "helm" => :optional
  depends_on "k3d" => :optional
  depends_on "kubectl" => :optional

  on_macos do
    on_intel do
      url "https://github.com/gautampachnanda101/homebrew-tap/releases/download/v1.0.4/k3d-local_1.0.4_Darwin_x86_64.tar.gz"
      sha256 "e05bd6ac88be2c369620d9822dd9da46e83fc4b42292f71de7e4aec718e612bb"

      def install
        bin.install "k3d-local"
      end
    end
    on_arm do
      url "https://github.com/gautampachnanda101/homebrew-tap/releases/download/v1.0.4/k3d-local_1.0.4_Darwin_arm64.tar.gz"
      sha256 "d846dcdc63032a7fbf69ace44c7e9b1247519588fed9413916c267bdd5b1be52"

      def install
        bin.install "k3d-local"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/gautampachnanda101/homebrew-tap/releases/download/v1.0.4/k3d-local_1.0.4_Linux_x86_64.tar.gz"
        sha256 "617b639e97877c3bfa88ace7976ac10324d43b64590a18b72731da2fb4e3e778"

        def install
          bin.install "k3d-local"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/gautampachnanda101/homebrew-tap/releases/download/v1.0.4/k3d-local_1.0.4_Linux_arm64.tar.gz"
        sha256 "6dd1918c91b3966725367f7904a66414485be5bc02e2d9732cbd8ad86d723ab5"

        def install
          bin.install "k3d-local"
        end
      end
    end
  end

  test do
    system "#{bin}/k3d-local", "version"
  end
end
