# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class K3dLocal < Formula
  desc "Cross-platform CLI for managing local k3d Kubernetes clusters with pre-configured components"
  homepage "https://github.com/gautampachnanda101/local-cluster-k3d"
  version "1.0.4"
  license "MIT"

  depends_on "docker" => :optional
  depends_on "helm" => :optional
  depends_on "k3d" => :optional
  depends_on "kubectl" => :optional

  on_macos do
    on_intel do
      url "https://github.com/gautampachnanda101/homebrew-tap/releases/download/v1.0.4/k3d-local_1.0.4_Darwin_x86_64.tar.gz"
      sha256 "4a05e2ef4934def6723115cb367ee4b831dc4982d23abff91e5e630e776114e8"

      def install
        bin.install "k3d-local"
      end
    end
    on_arm do
      url "https://github.com/gautampachnanda101/homebrew-tap/releases/download/v1.0.4/k3d-local_1.0.4_Darwin_arm64.tar.gz"
      sha256 "fe019f0c6df8bf4eeddaa16c49c9563cf73c334a540ffc52773f0696371a2905"

      def install
        bin.install "k3d-local"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/gautampachnanda101/homebrew-tap/releases/download/v1.0.4/k3d-local_1.0.4_Linux_x86_64.tar.gz"
        sha256 "45b5c5709c0bc47da557c381892a93b5e170dcc7320babc3b59d83b2715b03ed"

        def install
          bin.install "k3d-local"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/gautampachnanda101/homebrew-tap/releases/download/v1.0.4/k3d-local_1.0.4_Linux_arm64.tar.gz"
        sha256 "76200ea12393b842ec3bd7c21fecf0f51150f387641dd9c89a2770f373bc3d85"

        def install
          bin.install "k3d-local"
        end
      end
    end
  end

  test do
    system "#{bin}/k3d-local", "version"
  end
end
