apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: authentik

resources:
  - namespace.yaml
  - postgres.yaml
  - redis.yaml
  - secret.yaml
  - server.yaml
  - worker.yaml
  - service.yaml
  - certificate.yaml
  - ingress.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: authentik
