apiVersion: v1
kind: Secret
metadata:
  name: authentik-secret
  namespace: authentik
type: Opaque
stringData:
  AUTHENTIK_SECRET_KEY: "THIS-IS-NOT-A-SECURE-KEY-CHANGE-ME"
  AUTHENTIK_POSTGRESQL__PASSWORD: "authentik"
