apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: keycloak

resources:
  - ../../base

patches:
  - target:
      kind: Certificate
      name: keycloak-tls
    patch: |-
      apiVersion: cert-manager.io/v1
      kind: Certificate
      metadata:
        name: keycloak-tls
      spec:
        issuerRef:
          name: letsencrypt-prod
          kind: ClusterIssuer
        dnsNames:
          - DOMAIN.PLACEHOLDER
  
  - target:
      kind: IngressRoute
      name: keycloak
    patch: |-
      apiVersion: traefik.io/v1alpha1
      kind: IngressRoute
      metadata:
        name: keycloak
      spec:
        routes:
          - match: Host(`DOMAIN.PLACEHOLDER`)
            kind: Rule
            services:
              - name: keycloak
                port: 8080
  
  - target:
      kind: Deployment
      name: keycloak
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: keycloak
      spec:
        replicas: 2
        template:
          spec:
            containers:
            - name: keycloak
              args:
              - start
              - --optimized
              env:
              - name: KC_HOSTNAME_URL
                value: "https://DOMAIN.PLACEHOLDER"
              resources:
                requests:
                  memory: "1Gi"
                  cpu: "500m"
                limits:
                  memory: "2Gi"
                  cpu: "1000m"
