apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  # Install official ArgoCD
  - https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
  - certificate.yaml
  - ingress.yaml

# Patch argocd-server to run in insecure mode (TLS handled by Traefik)
patches:
  - target:
      kind: Deployment
      name: argocd-server
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: argocd-server
      spec:
        template:
          spec:
            containers:
              - name: argocd-server
                command:
                  - argocd-server
                  - --insecure

# Common labels
labels:
  - pairs:
      app.kubernetes.io/part-of: argocd
